export const data = {
  name: 'Touseef Ur Rehman',
  phoneNumber: +923119996341,
  email: 'touseefibnkhalil@gmail.com',
  linkedinUrl: 'https://linkedin.com/in/touseefcodes',
  githubUrl: 'https://github.com/realtouseef',
  websiteUrl: 'https://touseef.vercel.app',
  skills: [
    [
      'JavaScript',
      'TypeScript',
      'ReactJS',
      'NextJS 14',
      'ExpressJS',
      'Mongoose',
      'MongoDB',
      'Git',
      'GitHub',
      'AWS S3',
    ],
    [
      'Redux Toolkit',
      'GraphQL',
      'Firebase Authentication',
      'TailwindCSS',
      'Bootstrap',
      'Chakra-UI',
    ],
  ],
  experience: [
    {
      position: 'FullStack Engineer',
      startDate: '11/2022',
      endDate: 'Present',
      companyName: 'Productbox',
      companyLink: 'https://productbox.dev',
      description: [
        'Skilled in using technologies such as JavaScript, ReactJS, CSS, React Hook Form, and Yup validation to deliver high-quality, maintainable code.',
        'Proficient in integrating APls and third-party services to create robust and scalable web applications.',
        'Collaborating closely with cross-functional teams, including designers, product managers, and QA engineers, to deliver complex tasks on time and to the highest quality standards.',
      ],
    },
    {
      position: 'FullStack Engineer',
      startDate: '01/2023',
      endDate: '04/2023',
      companyName: 'MetaKlouds',
      companyLink: 'https://www.linkedin.com/company/metaklouds/',
      description: [
        'Developing a SaaS product similar to Behance and Dribbble',
        'Using NextJS, TailwindCSS, React Hook Form, and Yup for validation to convert complex designs from Figma to an actual website.',
        'Participated in daily standup meetings to report progress to product manager.',
        `Collaborated with team members to ensure project is completed on time and to client's satisfaction.`,
      ],
    },
  ],
  education: {
    first: {
      degree: 'BS. Computer Science',
      university: 'Agriculture University Peshawar',
      startDate: '08/2017',
      endDate: '08/2021',
      description: ['Did my bachelors from Agriculture'],
    },
    second: {
      degree: 'Pre-Engineering',
      university: 'Warsak Model School & College',
      startDate: '04/2015',
      endDate: '05/2017',
      description: ['Did my Pre-engineering from Warsak Model'],
    },
  },
  projects: [
    {
      projectName: 'Palitics',
      startDate: '04/2024',
      endDate: '06/2024',
      onSite: false,
      projectLink: 'https://palitics.co.uk',
      description: [
        'Palitics empowers individuals to make a significant impact on the political landscape',
        'Handling over 25K+ monthly users, demonstrating its potential to make a significant impact in the online space',
        'Played a key role in creating this platform that empowered voters by providing data-driven insights into the true power of their vote, enabling them to make informed decisions and shape a brighter, fairer future for everyone.',
      ],
    },
    {
      projectName: 'Masonry',
      startDate: '10/2023',
      endDate: '10/2023',
      onSite: false,
      projectLink: 'https://www.npmjs.com/package/@tx666/masonry',
      description: [
        'Achieved over 500+ downloads of the package within the first 20 hours, indicating high demand and adoption of the solution in the React community.',
        'Leveraged TypeScript to enhance code organization, maintainability, and error detection in the front-end solution.',
      ],
    },
    {
      projectName: 'QuranFan',
      startDate: '11/2021',
      endDate: '12/2021',
      onSite: false,
      projectLink: 'https://quranfan.vercel.app/',
      description: [
        'Provides easy access to Quranic verses based on emotions like sadness, depression, and hopelessness, offering comfort and guidance.',
        'Offers Quranic verses with Urdu and English translations, making them accessible to a wider audience.',
        'Includes a feature to randomly pick a verse from the Quran, adding an element of inspiration.',
        'Allows users to search for specific words or phrases in the Quran, enabling targeted exploration of the holy text.',
        `Promotes the study and understanding of the Quran by making its verses more accessible and relatable to people's emotional experiences.`,
      ],
    },
    {
      projectName: 'Noorify',
      startDate: '11/2023',
      endDate: '12/2023',
      onSite: false,
      projectLink: 'https://www.npmjs.com/package/@tx666/masonry',
      description: [
        'Enables users to create high-quality, aesthetically pleasing images with verses from the Quran, without the need for complex photo editing software.',
        'Simplifies the process of adding Quranic verses to images, making it accessible to a wider audience, including those with limited design skills.',
        'Promotes the sharing and appreciation of Quranic verses through visually appealing, shareable images on social media and other platforms.',
        'Helps individuals and organizations create inspirational, faith-based content for personal, educational, or religious purposes.',
      ],
    },
    {
      projectName: 'LevelId',
      startDate: '01/2024',
      endDate: '03/2024',
      onSite: false,
      description: [
        'Played a key role in developing the Leveld.ai platform, which aims to level the playing field for companies delivering projects, making project management more accessible and approachable for a wider audience.',
        'Utilized Next.js and TypeScript to craft a responsive and intuitive frontend for Leveld.ai, enhancing the user experience and simplifying project management for all users.',
      ],
    },
    {
      projectName: 'meraID',
      startDate: '11/2022',
      endDate: 'Present',
      onSite: true,
      description: [
        `meraID is Pakistan's first e-identity mobile application that represents your identity in a digital form as an electronic identity (e-ID).`,
      ],
    },
    {
      projectName: 'PixelSouk',
      startDate: '01/2023',
      endDate: '05/2023',
      onSite: false,
      description: [
        `PixelSouk is a marketplace for digital art and designs where sellers are content creator/designers`,
      ],
    },
  ],
};
